services:
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        ports:
            - "9411:9411"

    otel-collector:
        image: otel/opentelemetry-collector:latest
        container_name: otel-collector
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "1888:1888" # pprof extension
            - "8888:8888" # Prometheus metrics exposed by the collector
            - "8889:8889" # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "4317:4317" # OTLP gRPC receiver
            - "4318:4318" # OTLP HTTP receiver
            - "55670:55679" # zpages extension
        depends_on:
            - zipkin

    app-a:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-a
        ports:
            - "8080:8080"
        volumes:
            - ./service_a:/app

    app-b:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-b
        environment:
            - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
            - SERVICE_A_URL=http://app-a:8080
        ports:
            - "8081:8081"
        volumes:
            - ./service_b:/app
        depends_on:
            - otel-collector
